### ISSUE TITLE
KeyError: 'umap_cell_embeddings'

### ISSUE THREAD

**Issue by kenneditodd** [pinellolab/singlecellvr#16]
I am trying to do singlecellVR starting from a seurat object.  I have tried with my own data and the pbmc example dataset shown.  I can convert to .loom just fine. I get a KeyError: 'umap_cell_embeddings' when i run scvr from my conda environment.

command: 
`scvr -f seurat3d_10xpbmc.loom -t seurat -a annotations.txt -g genes.txt -o seurat_report`

Standard output is shown below.  How do i fix this problem?
```
- Single cell VR preprocessing -
Version 1.1

Converting 'seurat' analysis result ...
reading in loom file ...
OMP: Info #271: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Traceback (most recent call last):
  File "/Users/m214960/miniconda3/envs/scvr/bin/scvr", line 8, in <module>
    sys.exit(main())
  File "/Users/m214960/miniconda3/envs/scvr/lib/python3.9/site-packages/scvr/command_line.py", line 93, in main
    scvr.output_seurat_cells(adata,ann_list,gene_list=gene_list,reportdir=output)
  File "/Users/m214960/miniconda3/envs/scvr/lib/python3.9/site-packages/scvr/converters.py", line 194, in output_seurat_cells
    assert (adata.obsm['umap_cell_embeddings'].shape[1]>=3),\
  File "/Users/m214960/miniconda3/envs/scvr/lib/python3.9/site-packages/anndata/_core/aligned_mapping.py", line 148, in __getitem__
    return self._data[key]
KeyError: 'umap_cell_embeddings'
```

**Comment by kenneditodd** [comment]
@qinqian  @davidfstein I still can't get it to work. This was my R chunk.
```
SaveH5Seurat(pbmc, filename = "pbmc3k.h5Seurat")
Convert("pbmc3k.h5Seurat", dest = "h5ad")
```
R output
```
Creating h5Seurat file for version 3.1.5.9900
Adding counts for RNA
Adding data for RNA
Adding scale.data for RNA
Adding variable features for RNA
Adding feature-level metadata for RNA
Adding cell embeddings for pca
Adding loadings for pca
No projected loadings for pca
Adding standard deviations for pca
No JackStraw data for pca
Adding cell embeddings for umap
No loadings for umap
No projected loadings for umap
No standard deviations for umap
No JackStraw data for umap
Validating h5Seurat file
Adding scale.data from RNA as X
Transfering meta.features to var
Adding data from RNA as raw
Transfering meta.features to raw/var
Transfering meta.data to obs
Adding dimensional reduction information for pca
Adding feature loadings for pca
Adding dimensional reduction information for umap
```
I created my conda environment like this
```
conda create -n scvr python=3.7
conda activate scvr
pip install scvr scvelo
```
Ran this command
```
scvr -f pbmc3k.h5ad -t seurat -a annotations.txt -g genes.txt -o seurat_report
```
This was my error
```
- Single cell VR preprocessing -
Version 1.1

Converting 'seurat' analysis result ...
Traceback (most recent call last):
  File "/Users/m214960/miniconda3/envs/scvr/bin/scvr", line 8, in <module>
    sys.exit(main())
  File "/Users/m214960/miniconda3/envs/scvr/lib/python3.7/site-packages/scvr/command_line.py", line 90, in main
    assert (filename.lower().endswith(('.loom'))), "For Seurat only .loom file is supported."
AssertionError: For Seurat only .loom file is supported.
```

Are you able to send a yaml file so i can make sure I have the same conda environment?

**Comment by qinqian** [comment]
We didn't update the scvr on the pypi, could you please `cd scvr && python setup.py install`? 

Best,
Qian

**Comment by kenneditodd** [comment]
@qinqian 
Okay I cloned the repository, did ``` cd scvr``` and then ```python setup.py install``` .  I am still getting the following error.
```
scvr -f pbmc3k.h5ad -t seurat -a annotations.txt -g genes.txt -o seurat_report
- Single cell VR preprocessing -
Version 1.1

Converting 'seurat' analysis result ...
Traceback (most recent call last):
  File "/Users/m214960/miniconda3/envs/scvr/bin/scvr", line 33, in <module>
    sys.exit(load_entry_point('scvr==1.1', 'console_scripts', 'scvr')())
  File "/Users/m214960/miniconda3/envs/scvr/lib/python3.7/site-packages/scvr/command_line.py", line 90, in main
    assert (filename.lower().endswith(('.loom'))), "For Seurat only .loom file is supported."
AssertionError: For Seurat only .loom file is supported.
```

Let me know if I did anything wrong or misunderstood.

**Comment by qinqian** [comment]
Please delete scvr in your directory first and then setup the new script. As the `assert` in the latest code is 93th line (https://github.com/pinellolab/singlecellvr/blob/master/scvr/scvr/command_line.py#L93).
